server:
  port: 8080

spring:
  application:
    name: api-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

app:
  kafka:
    topic:
      transaction-requests: transaction_requests
  security:
    verify:
      allowed-clock-skew: 2m
      nonce-enforced: false
      nonce-ttl: 2m
      merchants:
        merchant-demo:
          salt-key: ${APP_MERCHANT_DEMO_SALT_KEY:merchant-demo-secret-key}
          salt-index: "1"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
