spring:
  application:
    name: audit-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.kaustubh.transactions.common.event
        spring.json.value.default.type: com.kaustubh.transactions.common.event.TransactionLogEvent
    listener:
      ack-mode: manual

  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_audit

app:
  kafka:
    listener:
      concurrency: 3
    topic:
      transaction-log: transaction_log
