package com.kaustubh.transactions.api.controller;

import java.util.Map;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.kaustubh.transactions.api.security.VerifySignatureFilter;
import com.kaustubh.transactions.api.service.TransactionIngressService;
import com.kaustubh.transactions.common.api.CreateTransactionRequest;
import com.kaustubh.transactions.common.api.CreateTransactionResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

@RestController
@RequestMapping("/api/v1/transactions")
@Tag(name = "Transaction API", description = "Transaction submission and status endpoints")
@RequiredArgsConstructor
public class TransactionController {

    private final TransactionIngressService transactionIngressService;

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "Submit a transaction",
            description = "Accepts a signed transaction request, publishes it for asynchronous processing, and returns an acknowledgment.",
            parameters = {
                    @Parameter(
                            name = "X-Merchant-Id",
                            in = ParameterIn.HEADER,
                            required = true,
                            description = "Merchant identifier used to resolve signing configuration.",
                            example = "merchant-demo"
                    ),
                    @Parameter(
                            name = "X-Timestamp",
                            in = ParameterIn.HEADER,
                            required = true,
                            description = "ISO-8601 UTC timestamp generated by the client for request signing.",
                            example = "2026-03-20T10:15:30Z"
                    ),
                    @Parameter(
                            name = "X-Nonce",
                            in = ParameterIn.HEADER,
                            required = true,
                            description = "Unique client-generated nonce used to prevent replay attacks.",
                            example = "550e8400-e29b-41d4-a716-446655440000"
                    ),
                    @Parameter(
                            name = "X-Verify",
                            in = ParameterIn.HEADER,
                            required = true,
                            description = "Request signature in the format <HEX_SHA256>###<saltIndex>.",
                            example = "8F4A8C2D4D6B5A4C7E1F9A6B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1###1"
                    ),
                    @Parameter(
                            name = "Idempotency-Key",
                            in = ParameterIn.HEADER,
                            required = true,
                            description = "Unique client-generated key used to prevent duplicate submissions.",
                            example = "idem-20260320-0001"
                    ),
                    @Parameter(
                            name = "X-Correlation-Id",
                            in = ParameterIn.HEADER,
                            required = false,
                            description = "Optional correlation identifier used for tracing across services.",
                            example = "corr-20260320-0001"
                    )
            }
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "202",
                    description = "Transaction accepted for asynchronous processing",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = CreateTransactionResponse.class),
                            examples = @ExampleObject(
                                    name = "accepted",
                                    value = """
                                            {
                                              "transactionId": "7d9d7f5d-19c4-4d7d-8f2a-6d92c7d90f61",
                                              "status": "RECEIVED"
                                            }
                                            """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request payload",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ValidationErrorResponse.class),
                            examples = @ExampleObject(
                                    name = "validationError",
                                    value = """
                                            {
                                              "timestamp": "2026-03-20T10:15:30Z",
                                              "status": 400,
                                              "error": "Validation failed",
                                              "fieldErrors": {
                                                "amount": "amount must be greater than 0",
                                                "currency": "currency is required"
                                              }
                                            }
                                            """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "401",
                    description = "Missing or invalid authentication headers",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ErrorResponse.class),
                            examples = {
                                    @ExampleObject(
                                            name = "missingHeaders",
                                            value = """
                                                    {
                                                      "error": "Missing required auth headers"
                                                    }
                                                    """
                                    ),
                                    @ExampleObject(
                                            name = "invalidSignature",
                                            value = """
                                                    {
                                                      "error": "Invalid signature"
                                                    }
                                                    """
                                    )
                            }
                    )
            )
    })
    public ResponseEntity<CreateTransactionResponse> createTransaction(
            @Parameter(hidden = true)
            @RequestHeader(value = VerifySignatureFilter.HEADER_MERCHANT_ID, required = false) String merchantId,
            @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    required = true,
                    description = "Transaction request payload",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = CreateTransactionRequest.class),
                            examples = {
                                    @ExampleObject(
                                            name = "creditTransaction",
                                            summary = "Credit transaction request",
                                            value = """
                                                    {
                                                      "idempotencyKey": "idem-20260320-0001",
                                                      "accountId": "acct-1001",
                                                      "amount": 1500.75,
                                                      "currency": "INR",
                                                      "type": "CREDIT",
                                                      "callbackUrl": "https://merchant.example/webhook"
                                                    }
                                                    """
                                    ),
                                    @ExampleObject(
                                            name = "debitTransaction",
                                            summary = "Debit transaction request",
                                            value = """
                                                    {
                                                      "idempotencyKey": "idem-20260320-0002",
                                                      "accountId": "acct-2007",
                                                      "amount": 499.99,
                                                      "currency": "INR",
                                                      "type": "DEBIT"
                                                    }
                                                    """
                                    )
                            }
                    )
            )
            @RequestBody @Valid CreateTransactionRequest request
    ) {
        CreateTransactionResponse response = transactionIngressService.accept(request, merchantId);
        return ResponseEntity.accepted().body(response);
    }

    @Schema(name = "ValidationErrorResponse", description = "Validation error response")
    public record ValidationErrorResponse(
            @Schema(example = "2026-03-20T10:15:30Z") String timestamp,
            @Schema(example = "400") int status,
            @Schema(example = "Validation failed") String error,
            @Schema(
                    description = "Field-level validation errors",
                    example = "{\"amount\":\"amount must be greater than 0\",\"currency\":\"currency is required\"}"
            ) Map<String, String> fieldErrors
    ) {
    }

    @Schema(name = "ErrorResponse", description = "Error response body")
    public record ErrorResponse(
            @Schema(example = "Invalid signature") String error
    ) {
    }
}
